Fix input data from i2s_bidi_slave program
malacalypse/rp2040_i2s_example pull request #8
Opened 2023-02-28 09:39 UTC by murdo-g

Thanks for sharing this great example. 

I was having issues using the **i2s_bidi_slave** program with an SGTL5000 codec. Input data appeared to be bit shifted resulting in heavy distortion.

I restructured the PIO program to more closely resemble the **i2s_in_slave** program which fixed the issue in my case and thought I'd share it.

From the sounds of things this is the same issue users mentioned in #6.

2023-03-04 21:12 UTC, malacalypse requested changes
I'll be happy to accept this after the last line is removed. Please leave the comment (and line up the semicolon with the line above it, something like:

```
  jmp pin loop_r                ; if LRCK is still high, we're still sampling this word
                                ; implicit jmp to start_l: otherwise, start the loop over
```

Would be nice. If you want to do the same thing at line 158 (last line of the audio input PIO) that'd be cool too.  Thank you!

2023-03-04 21:12 UTC, malacalypse commented on i2s.pio
> +  jmp start_l                   ; otherwise, start the loop over
Please delete this last jump, it's unnecessary.

2023-03-06 09:39 UTC, murdo-g commented
Removed the final jump instructions for both **i2s_bidi_slave** and **i2s_in_slave**

2023-03-06 20:26 UTC, malacalypse approved these changes

2023-03-06 20:26 UTC, merged

2023-03-06 20:26 UTC, malacalypse commented
Thanks @murdo-g for taking the time to do that.